### ISSUE TITLE
Add back missing high level fields (lost in work on CAP specific fields.

### ISSUE THREAD

**Issue by dosumis** [cellannotation/cell-annotation-schema#106]
Compare 
https://github.com/cellannotation/cell-annotation-schema/blob/main/docs/cap_anndata_schema.md#uns-dataset-metadata
to 
https://github.com/cellannotation/cell-annotation-schema/blob/main/build/general_schema.md#properties

An property with CAP in the name in the CAP anndata schema should go in the CAP extension (some may already be there).  The rest should go in general.

**Comment by ubyndr** [comment]
Hi @dosumis , Do I need to add fields from the [Cell Annotation Metadata](https://github.com/cellannotation/cell-annotation-schema/blob/main/docs/cap_anndata_schema.md#cell-annotation-metadata) to the annotations in the CAP extension?
