### ISSUE TITLE
Build should update on PR merge

### ISSUE THREAD

**Issue by dosumis** [cellannotation/cell-annotation-schema#107]
Is it possible to trigger build on PR merge so that this folder remains up to date? https://github.com/cellannotation/cell-annotation-schema/tree/main/build. This would make collaboration much easier.

**Comment by hkir-dev** [comment]
The GitHub Action for building is triggered upon updates to the main branch. You can view the configuration here: [Build GitHub Action workflow](https://github.com/cellannotation/cell-annotation-schema/blob/44fcfbe850971fd5a07dfa4656da0b9a22deacbe/.github/workflows/build_main.yaml#L6).

Please let us know if it does not work as expected.

**Comment by ubyndr** [comment]
Hello @dosumis, let's merge https://github.com/cellannotation/cell-annotation-schema/pull/103 and verify if it functions as expected. It's expected to work seamlessly. Once you confirm that https://github.com/cellannotation/cell-annotation-schema/pull/103 is ready for merging, please notify us, and I'll proceed accordingly.

**Comment by dosumis** [comment]
Yeh - I think I was just confused.  Apologies.  #103 might not be ready to merge but I have some simpler issues that need fixing that I can make PRs for ASAP.

**Comment by ubyndr** [comment]
The action is working as expect with either pushes to main branch or PR merges;
![image](https://github.com/cellannotation/cell-annotation-schema/assets/20892222/2c50060b-9ff7-4d88-83cb-697eeabd9c15)
