### ISSUE TITLE
Include more than one external URLs, contact name + email

### ISSUE THREAD

**Issue by ubyndr** [cellannotation/cell-annotation-schema#117]
Copied from [MVP-5401](https://capdevelopment.atlassian.net/browse/MVP-5401)

We might have to make changes to CAS based on the changes above. Please speak with David OS.

- [ ] [MVP-5416](https://capdevelopment.atlassian.net/browse/MVP-5416), Allow more than one external URL [CAS schema review & changes]
- [ ] [MVP-5420](https://capdevelopment.atlassian.net/browse/MVP-5420), Allow multiple contact name + contact email  [CAS schema review & changes]

**Comment by dosumis** [comment]
I think we can support [MVP-5420](https://capdevelopment.atlassian.net/browse/MVP-5420), with  #102

**Comment by dosumis** [comment]
superseded  by #102
