### ISSUE TITLE
Write SOP for & functional specifications for writing and converting spreadsheets to CAS

### ISSUE THREAD

**Issue by dosumis** [cellannotation/cell-annotation-schema#25]
This will provide guidance for data wranglers on how to structure their curation and specifications for a script to  convert curated spreadsheets to CAS.  It could also  be useful for any table-based editing tools using CAS - e.g. https://github.com/brain-bican/taxonomy-development-tools

**Comment by dosumis** [comment]
@mfutey  - It looks like your curated sheets are already very close to schema compliance - we need to work on aligning and an SOP for curation.  @ubyndr can then write python scripts to generate CAS JSON and flatten to anndata.

TBD: how we derive lists of cell IDs (will this be done by your upstream or as part of scripts using curated sheets + anndata file?

**Comment by mfutey** [comment]
For some of the retina sheets I modified the field names to be more informative for the researcher who filled them in, I can easily update these to be inline with the schema. 

@evanbiederstedt wrote a script for extracting the barcodes for upstream use which was something we did as a temporary solution. We should define how we want to do this in the SOP.

**Comment by dosumis** [comment]
See also https://github.com/cellannotation/cap_file_planning/issues/10

**Comment by ubyndr** [comment]
This has been completed with https://github.com/cellannotation/cas-tools/issues/34, the implementation of it has been completed as well.
