### ISSUE TITLE
Add release mechanism

### ISSUE THREAD

**Issue by dosumis** [cellannotation/cell-annotation-schema#27]
Release should merge in extension files to produce release products

core schema,
bican_schema,
cap_schema.

It would also be useful to have a snapshot release (tag set?) that runs nightly/on-demand so that we can easily review merged products.

**Comment by hkir-dev** [comment]
Related GitHub actions implemented. Draft Snapshot release can be found at: https://github.com/cellannotation/cell-annotation-schema/releases
