### ISSUE TITLE
Supporting multiple authors

### ISSUE THREAD

**Issue by dosumis** [cellannotation/cell-annotation-schema#41]
As currently defined, the field only allows for a single author.  This is unrealistic.  Author ORCID is a second field, author contact is a third field. Having 3 lists is dangerous (fencepost issues).  I suggest instead we define an author object and encode a list of these objects in CAS.

**Comment by dosumis** [comment]
Issue - relationship to CAP author/Pub fields in CAP schema repo.

**Comment by evanbiederstedt** [comment]
The CAP solution:

- One author is the CAP user who clicks publish
- Other others are listed via whomever has write permission to CAP

It's tricky as there are multiple use cases here

**Comment by ubyndr** [comment]
see also #44

**Comment by dosumis** [comment]
CAP_anndata_file spec currently supports this with an additional field for secondary authors ( cap_publication_authors_list).

Options to make this generic:
-  Make Primary (corresponding) author and scondary/other authors fields?
-  One field and first entry is considered primary author?

TO make things more complex - CCN1 allowed recording of different authors for individual annotations.  This was quite widely used.

**Comment by dosumis** [comment]
We should align with CAP solution.   They now have generic field names for authors.  @ubyndr - Please add all of these to general schema.  

Thanks!
