### ISSUE TITLE
Add support for writing minimal Anndata conversion + tools for querying

### ISSUE THREAD

**Issue by dosumis** [cellannotation/cell-annotation-schema#42]
Minimal representation: 

- [x] cellannotation/cas-tools#6
    - input CAS JSON schema file; AnnData file (ideally AnnData file location will be specified by resolvable path in CAS file)
    - Checks before writing:
        - Do all barcodes (cell IDs)  in CAS file exists in AnnData file -  if not, warn if not with option to terminate.
        - Do all barcodes (cell IDs) in AnnData file exist in CAS file -  if not, warn if not with option to terminate.
        - Do any obs keys in the AnnData file match labelset names in CAS - if they do warn - with options to overwrite or terminate. 
   - Store JSON in uns (dropping barcodes) 
   - Write labelset:cell_label pairs in obs - this replaces barcode lookup.
    
- [ ] Write Python tools for extracting and displaying additional annotation data on request.
   - function to write a dataframe of annotations
   - function to return details of any single annotation
   - function to return general metadata about annotations
   - function to return general metadata about labesets

Note - For better modularisation, we may move code to here https://github.com/cellannotation/castool (TBD)

**Comment by hkir-dev** [comment]
I have a project for CAS operations. We can improve it together if it will help.
https://github.com/hkir-dev/cell-type-annotation-tools/tree/tdt_sprint2
https://pypi.org/project/ctat/

I am using this project to:
- convert user data to CAS compliant format using a config
- exporting CAS formatted data in json format (to be used by the [taxonomy development tools](https://github.com/brain-bican/taxonomy-development-tools) primarily)
- exporting CAS formatted data into tables (to be used by the [taxonomy development tools](https://github.com/brain-bican/taxonomy-development-tools) primarily)

**Comment by dosumis** [comment]
@hkir-dev - strongly agree we should discuss merging efforts.
