### ISSUE TITLE
Publish - Siletti whole brain datset in CAS

### ISSUE THREAD

**Issue by dosumis** [cellannotation/cell-annotation-schema#53]
Status: Draft

This is an EPIC intended for grouping tasks.  Component tasks should have single assignees on their own tickets.

Publication of Siletti whole brain datset in CAS is needed to BICAN and will serve as a public showcase of a dataset annotated using with CAS (BICAN extension).  Publication should be as CAS and AnnData following both expanded and minimal conversions.

Dependencies: 

Current curation in spreadsheets needs to be finalised (approval from authors pending) @mfutey & @dosumis to finalise. and standardised - see cellannotation/cell-annotation-schema#25 
Scripts/pipelines need to be in place to convert spreadsheets to CAS.  @ubyndr 
Scripts needed to pull barcode lists from anndata files - e.g. see https://github.com/cellannotation/cell_bx_extractor/blob/main/bx_extractor_script.py
and to generate BICAN-compliant checksum-based cell-set accessions. @hkir-dev / @ubyndr 
AnnData conversion scripts need to be written, released and tested. @ubyndr  cellannotation/cas-tools#7  cellannotation/cell-annotation-schema#42

**Comment by dosumis** [comment]
This is now working to the point where we have a high quality draft conversion.  Can this be moved to it's own repo with a PURL release.? Two files: non-neuronal and neurons.

**Comment by hkir-dev** [comment]
Repos:
- https://github.com/brain-bican/human-brain-cell-atlas_v1_neurons
- https://github.com/brain-bican/human-brain-cell-atlas_v1_non-neuronal

PURLs:
- https://purl.brain-bican.org/taxonomy/CCN202210140/CS202210140_neurons.json
- https://purl.brain-bican.org/taxonomy/CCN202210140/CS202210140_non-neuronal.json
