### ISSUE TITLE
Clean up repo

### ISSUE THREAD

**Issue by mfutey** [cellannotation/cell-annotation-schema#70]
I wanted to make a suggestion that we clean up the repo as it is public facing and might be confusing for users. Removing, organizing or renaming files could help make it easier to navigate.

**Comment by dosumis** [comment]
AFAIK, the only unused files are 
- [general_schema.md](https://github.com/cellannotation/cell-annotation-schema/blob/main/general_schema.md)
- [anndata_file_general.md](https://github.com/cellannotation/cell-annotation-schema/blob/main/anndata_file_general.md)

We could organise the top level a bit better - pushing content down into subdirectories. 

There is also a long-standing ticket on providing better automated documentation: https://github.com/cellannotation/cell-annotation-schema/issues/48

Having this at the top level would make it easier for users to understand.  We can also link to some notebooks on CAS-Tools now that code for working between CAS and AnnData is nearly ready.

**Comment by evanbiederstedt** [comment]
> We could organise the top level a bit better - pushing content down into subdirectories.

This would be nice

**Comment by hkir-dev** [comment]
Basic clean up completed:

- Folder structure improved
- Markup files moved to https://github.com/cellannotation/cell-annotation-schema/tree/main/docs folder
