### ISSUE TITLE
BICAN use case - track multiple annotation transfers onto a single cell set

### ISSUE THREAD

**Issue by dosumis** [cellannotation/cell-annotation-schema#8]
Use case: As a Brain Initiative taxonomy developer, I want to be able to keep track of annotation transfer from multiple sources onto individual nodes in my taxonomy - tracking the transferred label, the algorithm, and the reference taxonomy and dataset.
I want this to be stable to changes in nomenclature in the reference taxonomy.  See https://github.com/cellannotation/cell-annotation-schema/blob/main/user_stories.md#bican

Option 1: 
 - Use the existing schema.  Each annotation is a new cell set.

Challenges 

- how to name cell_annotation_keys (note - each key may not cover the whole set of cells in a dataset)
- how to indicate what cell set the transfer is to...

A not very satisfactory sketch: 

```JSON
 { "cell_annotation_key": "Subclass",
     "label": "D1 matrix",
     "cell_ontology_term": "matrix D1 medium spiny neuron",
     "cell_ontology_term_id": "CL:4030043",
     "Accession": "CCN20230822_204",
},
{ "cell_annotation_key":"CN20190214",  // Name of taxonomy transferred from
   "Accession": "CCN20230822_510",  // Is this confusing?
   "label": "D1m",
   "provenance": {
   "automated_annotation": {
   "algorithm_name": "scraatch_v1",  
   "transferred_to": "CCN20230822_204", // relationship to another cell set in this taxonomy
   "reference_dataset": ""
   }
}
```

Option 2: Schema extension

Sketch
```JSON

 { "cell_annotation_key": "Subclass",
     "cell_label": "D1 matrix",
     "Annotation_transfers": [
       { "label": "D1m",
         "taxonomy": "http://bican.org/taxonomy/1.1/CN20190214",  //versioned PURL
         "transferred_from": "CN20190214_1",  // ID of cluster in 
         "algorithm_name": "scrattch_v1"
       },
       {
        "label": "fubar",
        "taxonomy": "http://bican.org/taxonomy/1.1/CN20190214",  //versioned PURL
        "transferred_from": "CN20201225_42",
        "algorithm_name": "scMap_v3"
        }
    ]
}
```

Conclusion - Option 2 is much more transparent and easy to implement.  Suggest we add this extension.  It can be a separate object under an optional key in the Annotation object.

**Comment by ubyndr** [comment]
@dosumis to review

**Comment by dosumis** [comment]
Fixed  - see https://github.com/cellannotation/cell-annotation-schema/blob/main/BICAN_extension.json#L9 & https://github.com/cellannotation/cell-annotation-schema/blob/main/examples/BICAN_schema_specific_examples/Silletti_annotation_transfer.json
